# Generated by Django 3.1.5 on 2021-01-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='k_user',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=6)),
                ('branch', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('birth', models.DateField(max_length=16)),
                ('sex', models.CharField(max_length=2)),
                ('mig', models.CharField(max_length=50)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='k_user_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.CharField(max_length=25)),
                ('branch_now', models.CharField(max_length=30)),
                ('service_time', models.IntegerField(verbose_name=5)),
                ('rest_time', models.IntegerField(verbose_name=5)),
                ('exit_time', models.DateField(max_length=16)),
                ('user_phone', models.ForeignKey(db_column='user_phone', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.k_user')),
            ],
        ),
    ]
